# Welcome to Jekyll!

# Website settings
title: Lewis Wright - PHP freelancer in Manchester
description: I am a full stack developer living in Manchester. I specialise in Symfony and Meteor but I have a huge amount of experience in a number of technologies and roles. I write fast, secure and scalable software for businesses and am a huge proponent of BDD/TDD.
keywords: php,freelancer,manchester,salford,node,javascript,meteor,angular,react,tdd,bdd
baseurl:  /
url: http://allwrightythen.com
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Lewis Wright # Be used at blog posts' author.
  first_name: Lewis # Be used at index page about me section.
  last_name: Wright  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.png  # upload your avatar at directory and edit it.
  github_username: LewisW  # Leave blank if you don't have now
  linkedin_id: lewispwright # Leave blank if you don't have now
  facebook_username:  # Leave blank if you don't have now
  twitter_username: allwrightythen  # Leave blank if you don't have now
  email: lewis@allwrightythen.com  # Leave blank if you don't have now
  cv: # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-nodejs
    - name: icon-php-alt
  skill_icon2:
    - name: icon-symfony
    - name: icon-docker
  desc:  I am a full stack developer living in Manchester. I specialise in Symfony and Meteor but I have a huge amount of experience in a number of technologies and roles. I write fast, secure and scalable software for businesses and am a huge proponent of BDD/TDD.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: allwrightythen

# analytics
## google analytics
ga: UA-55974365-1

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
